---
functional:
  - Пользователь может авторизоваться через электронную почту
  - Пользователь не может авторизоваться под ранее незарегистрированной почтой
  - Пользователь может авторизоваться через Github
  - Пользователь может авторизоваться через Discord
  - Пользователь может зарегистрироваться с помощью электронной почты
  - Неавторизованный пользователь может создать пробную игру
  - Авторизованный пользователь может создать игру
  - Авторизованный пользователь может подключиться к игре
  - Авторизованный ользователь может посмотреть историю игр
  - Авторизованный пользователь может создать турнир
  - Авторизованный пользователь может создать игру с 4 уровнями сложности
  - У авторизованного пользователя отображается статус игры
  - Каждый игрок может видеть код своего соперника в режиме он-лайн
  - Каждый игрок имеет кнопку 'check' для проверки своего решения
  - Ограничений на количество проверок решения нет
  - Если один игрок вылетел из игры, второй продолжает играть
  - После вылета игрок может вернуться в игру, пока она не закончена
  - Пользователь может выбрать язык для задачи игры
  - Пользователь может сдаться в игре
  - Пользователь может наблюдать за игрой других пользователей
  - Внутри каждой игры есть отдельный чат с соперником
  - На главной странице есть чат
  - В чате главной страницы отображается список пользователей
  - В чате главной страницы отображается автор сообщения
  - Сайт должен быть удобным на мобильном устройстве

non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт работает через sockets
  - Решение пользователя проверяется с использованием docker

implicit:
  - Пользователь может приобрести премиум-доступ для просмотра истории игр
  - Пользователь может настраивать звуки в игре
  - Пользователь может прилинковать к своему аккаунту Discord
  - Пользователь может прилинковать к своему аккаунту Github
  - В шапке сайта авторизованного отображается количество пользователей онлайн, значок доступных приглашений к игре, имя пользователя, его ранг, рейтинг и кликабельная иконка профиля
  - Авторизованный пользователь может оставить обратную связь через кнопку "Send feedback"
  - На главной странице доступен список игр
  - Пользователь может восстановить забытый пароль


