---
functional:
  - Пользователь может авторизоваться через электронную почту
  - Пользователь не может авторизоваться под ранее незарегистрированной почтой
  - Пользователь может авторизоваться через Github
  - Пользователь может авторизоваться через Discord
  - Пользователь может зарегистрироваться с помощью электронной почты
  - Неавторизованный пользователь может запустить пробную игру
  - Авторизованный пользователь может создать игру с ботом
  - Авторизованный пользователь может подключиться к игре в листе ожидания
  - Авторизованный пользователь может создать турнир
  - Авторизованный пользователь может создать игру с 4 уровнями сложности
  - Пользователь может выиграть игру
  - Пользователь может сдаться в игре
  - Каждый игрок может видеть код своего соперника в режиме он-лайн
  - Каждый игрок может проверить свое решение
  - Нет ограничений на количество проверок решения 
  - Если один игрок покинул игру, второй может продолжать игру
  - После вылета игрок может вернуться в игру, пока она не закончена
  - Пользователь может выбрать язык для решения задачи в игре
  - Пользователь может наблюдать за игрой других пользователей в реалтайме
  - Внутри каждой игры есть отдельный чат с соперником
  - На главной странице есть чат для пользователей
  - В чате главной страницы отображается список пользователей
  - В чате главной страницы отображается автор сообщения
  - Сайт должен быть удобным на мобильном устройстве

non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт работает через sockets
  - Решение пользователя проверяется с использованием docker

implicit:
  - Пользователь может приобрести премиум-доступ для просмотра истории игр
  - Пользователь может настраивать звуки в игре
  - Пользователь может прилинковать аккаунт почты к своему аккаунту Discord
  - Пользователь может прилинковать аккаунт почты к своему аккаунту Github
  - В шапке сайта авторизованного отображается количество пользователей онлайн, значок доступных приглашений к игре, имя пользователя, его ранг, рейтинг и кликабельная иконка профиля
  - Пользователь может оставить обратную связь в игровом окне через кнопку "Send feedback"
  - На главной странице в Lobby доступен список активных игр
  - На главной странице в Tournaments доступен список турниров
  - На главной странице в History отображается исптория законченных игр (только для премиум)
  - Пользователь может восстановить забытый пароль


