---
functional:
  - Пользователь может авторизоваться через электронную почту
  - Пользователь может авторизоваться через Github
  - Пользователь может авторизоваться через Discord
  - Пользователь может зарегистрироваться с помощью электронной почты
  - Пользователь может зарегистрироваться с помощью Github
  - Пользователь может зарегистрироваться с помощью Discord
  - Пользователь может создать пробную игру без регистрации/авторизации
  - Пользователь может создать игру с ботом
  - Пользователь может создать игру с зарегистрированными пользователями
  - Пользователь может создать игру для отправки ссылки на нее незарегистрированному пользователю
  - Пользователь может отменить приглашение в игру
  - Пользователь может присоединиться к играм, доступным на главной странице
  - Пользователь может посмотреть историю игр
  - Пользователь может создать турнир
  - У пользователя отображается статус игры
  - У пользователя отображается имя игрока
  - Пользователь может выбрать язык для отображения задачи игры
  - Пользователь может сдаться в игре
  - Пользователь может наблюдать за игрой других пользователей
  - На главной странице доступен список игр
  - Внутри каждой игры есть отдельный чат с соперником
  - На главной странице есть чат
  - В чате главной страницы отображается список пользователей
  - В чате главной страницы отображается автор сообщения
  - Сайт должен быть удобным на мобильном устройстве
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт работает через sockets
  - Решение пользователя проверяется с использованием docker

implicit:
  - Пользователь может приобрести премиум-доступ для просмотра истории игр
  - Пользователь может настраивать звуки в игре
  - Пользователь может прилинковать к своему аккаунту Discord
  - Пользователь может прилинковать к своему аккаунту Github
  - В шапке сайта авторизованного отображается количество пользователей онлайн, значок доступных приглашений к игре, имя пользователя, его ранг, рейтинг и кликабельная иконка профиля
  - Авторизованный пользователь может оставить обратную связь через кнопку "Send feedback"


